## File originally copied from https://github.com/wolfi-dev/os/blob/main/grpc.yaml
## Changes based on https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/grpc/APKBUILD
package:
  name: grpc
  version: 1.62.0
  epoch: 0
  description: The C based gRPC
  copyright:
    - license: Apache-2.0 AND BSD-3-Clause AND MIT
environment:
  contents:
    repositories:
      - 'https://dl-cdn.alpinelinux.org/alpine/v3.19/main'
      - 'https://dl-cdn.alpinelinux.org/alpine/v3.19/community'
    packages:
      - abseil-cpp-dev
      - alpine-sdk
      - autoconf
      - automake
      - benchmark-dev
      - c-ares-dev
      - ca-certificates-bundle
      - chrpath
      - cmake
      - libstdc++-dev
      - libtool
      - linux-headers
      - openssl-dev
      - protobuf-dev
      - re2
      - re2-dev
      - samurai
      - xxhash-dev
      - yaml-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc
      tag: v${{package.version}}
      expected-commit: f78a54c5ad4e058734aa9b2beb9459940e4de342

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/share/doc/grpc
      cmake -B _build -G Ninja \
      	-DCMAKE_BUILD_TYPE=None \
      	-DCMAKE_INSTALL_PREFIX=/usr \
      	-DCMAKE_CXX_STANDARD=17 \
      	-DBUILD_SHARED_LIBS=True \
      	-DgRPC_INSTALL=ON \
      	-DgRPC_CARES_PROVIDER=package \
      	-DgRPC_SSL_PROVIDER=package \
      	-DgRPC_ZLIB_PROVIDER=package \
        -DgRPC_PROTOBUF_PROVIDER=package \
      	-DgRPC_ABSL_PROVIDER=package \
        -DgRPC_RE2_PROVIDER=package \
      	-DgRPC_BENCHMARK_PROVIDER=package \
      	-DgRPC_BACKWARDS_COMPATIBILITY_MODE=OFF \
      	-DgRPC_BUILD_TESTS=OFF
      cmake --build _build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install _build

subpackages:
  - name: grpc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - grpc
    description: grpc dev

update:
  enabled: true
  github:
    identifier: grpc/grpc
    strip-prefix: v
    use-tag: true