# TODO: This will be rewritten to be reusable

name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Retrieve GPG Keys
      run: |
        mkdir -p keys/
        echo ${{ secrets.GPGKEY }} | base64 --decode > keys/key.rsa
        echo ${{ secrets.GPGKEY }} | base64 --decode > keys/key.rsa.pub
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm,linux/arm64,linux/s390x

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: "Build docker image"
      run: | 
        docker buildx build --build-arg package_path=community/grpc --build-arg package_install=grpc-dev --platform=linux/amd64,linux/arm,linux/arm64,linux/s390x --push -t rpkatz/ingress-grpc .